# Generated by Django 5.1.4 on 2024-12-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nodes", models.JSONField(default=list)),
                ("connections", models.JSONField(default=list)),
            ],
        ),
    ]

#purpose:
    #Track database changes
    #Allow multiple developers to maintain consistent database schemas
    #Enable rolling back database changes
    #Provide version control for database structure